= dap
Michael Gale https://github.com/mgale
:idprefix:
:name: dap
:toc: macro
:toclevels: 4

Diff and Patch (dap) is a tool inspired by https://meldmerge.org/ and https://github.com/google/diff-match-patch

toc::[]

[[purpose]]
== Purpose ==

dap was created while working with mono repos and changes need to be promoted between file system folders instead of a branch or tag. It is designed to allow the user to pull in specific change sets between the files instead of a full copy paste or rsync still operation.

If a difference between files exist a diff is displayed and the user is asked if they want to review and apply patches. If the user says no nothing happens and the operation is repeated for the next file. If the user says yes then the differences are broken up into chunks, a.k.a patches. Then each patch is reviewed and can either be applied or skipped.

=== Workflow ===

. Determine if the files differ
. Present a diff to the user and determine if they want to patch the file
. Present a list of patches or chunks of diff and let the user decided which ones to apply
. Save the changes


[[quick_overview]]
== Quick overview

dap requires 2 command line arguments, the first argument is the file or directory that should be patched, the location you want to push the changes into. The 2nd argument is the file or directory that you want to pull from.

The --dry-run option performs all the steps and confirmations with the exception of writing to the file system.


. Using dap:
+
.Show help
----
$ ./dap --help
SYNOPSIS:
    dap [--dry-run] [--help|-h|-?] [--report-only|-q] [--version|-V] [<args>]

OPTIONS:
    --dry-run           Dry-run skips updating the underlying file contents (default: false)

    --help|-h|-?        (default: false)

    --report-only|-q    Report only files that differ (default: false)

    --version|-V        (default: false)


----
+
.Report changes only
----
$ ./dap --report-only tests/smalldiff/t1.txt tests/smalldiff/t2.txt
Files tests/smalldiff/t1.txt and tests/smalldiff/t2.txt differ
----
+
.Diff and patch a file
----
$ ./dap --dry-run tests/smalldiff/t1.txt tests/smalldiff/t2.txt
#####################################################
#DiffOutPut: Appling diff to: tests/smalldiff/t1.txt from: tests/smalldiff/t2.txt
---
-  nodes_group_count  = 1
-  node_replica_count = 1
+  nodes_group_count  = 2
+  node_replica_count = 2
---
-  node_type          = "cache.t3.small"
+  node_type          = "cache.m5.large"
---
-  engine_version     = "5.0.6"
-  at_rest_encryption = true
+  engine_version     = "5.0.8"
+  at_rest_encryption = false
---
-  visibility_timeout_seconds  = 600
+  visibility_timeout_seconds  = 1200
---

#####################################################
Review patches and apply them? (y/n):
----
+
.Diff and patch a directory
----
$ ./dap tests/smalldiff tests/smalldiff
...
----

Here is a very large directory example:
----
$ ./dap --report-only tests/samelarge/hostA tests/samelarge/hostB/
Loading files from  tests/samelarge/hostA
Done
Loading files from  tests/samelarge/hostB/
Done
Scanned:        Files: 222220        Directories: 22222        Diffs: 0        Patched: 0        Skipped: 0        Errors: 0         Runtime: 4.554211126s
----
